connection:
  host: chirpstack.iut-blagnac.fr
  port: 1883
  topic: AM107/by-room/+/data
ecriture:
  fichiers:
    data: data
    alerte: alerte
  intervale: 10
collecte:
  - temperature
  - activity
  - co2
  - pressure
  - humidity
alerte:
  co2:
    min: 300.0
    max: 301.0
  humidity:
    min: 20.0
    max: 21.0
  pressure:
    min: 100.0
    max: 120.0
  temperature:
    min: 5.0
    max: 12.0
