name: ❌ Bug
description: Signaler un bug
title: "❌ "
labels: ["❌ Bug"]
body:
  - type: input
    id: contact
    attributes:
      label: Coordonnées de contact
      description: Comment pouvons-nous vous contacter si nous avons besoin de plus d'informations ?
      placeholder: email@exemple.com
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Sur quels navigateurs rencontrez-vous le problème ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Application IOT
  - type: textarea
    id: what-happened
    attributes:
      label: Qu'est-ce qui s'est passé ?
      description: Dites-nous également ce que vous attendiez qu'il se passe. N'hésitez pas à inclure des captures d'écran !
      placeholder: Dites-nous ce que vous voyez !
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Quelle version de notre application utilisez-vous ?
      options:
        - v1.0
        - v2.0
        - v3.0
        - v4.0
        - v5.0
        - v6.0
        - v7.0
        - v8.1
        - v8.2
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Sortie de programme pertinente
      description: Veuillez copier-coller toute sortie de programme pertinente. Cela sera automatiquement formaté en code, donc pas besoin de guillemets.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
        label: Confirmation
        description: Merci de regarder les <a href="https://github.com/IUT-Blagnac/SAE-3-01-DevApp-G11-DisguiseHub">issues ouvertes et fermées</a> afin de ne pas créer des doublons.
        options:
          - label: J'ai regardé les issues ouvertes et fermées
            required: true  
          - label: J'accepte de suivre le Code de conduite de ce projet
            required: true