name: 📄 Documentation
description: Rédiger une documentation
title: "📄 "
labels: ["📄 Documentation"]
body:
  - type: textarea
    id: about
    attributes:
      label: Description de la documentation
      description: Décrivez la documentation que vous souhaitez.
    validations:
      required: true
  - type: dropdown
    id: application
    attributes:
      label: Cela concerne ?
      multiple: true
      options:
        - Site e-commerce
        - Application IOT
