name: 💬 User Story
description: Une user story de l'application
title: "💬 "
labels: ["💬 User story"]
body:
  - type: input
    id: us
    attributes:
      label: User story
      description: Description de la story
      placeholder: En tant que [Persona], je veux [feature], afin que [raison].
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      description: Quelle est l'importance de cette user story pour le client ?
      options:
        - Must
        - Should
        - Could
        - Will
    validations:
      required: true
  - type: dropdown
    id: complexity
    attributes:
      label: Complexité
      description: Quelle est la complexité de cette user story pour les développeurs ?
      options:
        - Haute
        - Moyenne
        - Basse
      validations:
        required: true
  - type: textarea
    id: acceptation
    attributes:
      label: Critères d'acceptation
      description: Comment sera évaluée la satisfaction de cette user story, jeux de tests si disponibles, ...
  - type: dropdown
    id: application
    attributes:
      label: Application concernée
      description: Quelle est l'application concernée par cette user story ?
      options:
        - Site e-commerce
        - Application IOT
    validations:
      required: true
