= Cahier De Test - Disguise'Hub
:toc:
:toc-title: Sommaire

:Entreprise: Disguise'Hub
:Equipe:  

.Créé par : Angelo Nichele
Créé pour : Tester les fonctionnalités du site web Disguise'Hub

 



== I. Introduction
=== 1. Objet :
Ce document a été produit dans le cadre d'un projet d'élaboration d'un site de vente en ligne de déguisement pour tester les différentes fonctionnalités de ce dernier.


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. 


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Informations du client :
==== 1.1 Connexion compte client :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un compte client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau compte client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.1 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre de connexion au site s'ouvre. ^| Avoir le site d'ouvert ^|OK
^|All_I_C.2 ^|Cliquer sur "Je n'ai pas encore de compte". ^|La fenêtre de création d'un compte client s'ouvre ^|aucune ^|OK
^|All_I_C.3 ^|Compléter tous les champs en étant bien valides sauf un et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.4 ^|Rentrer un numéro de téléphone "vgvhch" et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.5 ^|Rentrer un mail "test@gmail." et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.6 ^|Rentrer un mot de passe inadéquat (sans majuscule par exemple) ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.7 ^|Compléter les champs et ne pas cliquer sur le CAPTCHA. ^|Bouton "s'inscrire" est grisé + incapacité à cliquer dessus ^|aucune ^|OK
^|All_I_C.8 ^|Compléter les champs en étant bien valides + cliquer sur le CAPTCHA ^|Bouton "s'inscrire" est orangé + on peut cliquer dessus et s'inscrire sur le site ^|OK
^|All_I_C.9 ^|Cliquer sur "J'ai déjà un compte" ^|Redirection vers la page de connexion ^|OK



|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Connexion au site
>|Objectif 4+| Vérifier qu'il est possible de se connecter au site avec un compte client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.10 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre de connexion au site s'ouvre.  ^|Avoir le site d'ouvert ^|OK
^|All_I_C.11 ^|Remplir les champs, cliquer sur le CAPTCHA et cliquer sur "Se connecter" ^|Renvoie sur la page des informations du client ^|aucune ^|OK
^|All_I_C.12 ^|Comme avec la création du compte client, si mauvaise saisie des différents champs et valider. ^|Blocage + pop-up. ^|aucune ^|OK
^|All_I_C.13 ^|Remplir les champs, etc + cliquer sur la case "Se souvenir de moi" ^|Renvoie sur la page des informations du client mais en se déconnectant, l'adresse mail du client reste préremplie ^|aucune ^|OK

|====

|====

>|Cas de test 4+|Test-01-01-03
>|Titre 4+|Connexion au site avec le mot de passe oublié
>|Objectif 4+| Vérifier qu'il est possible de se connecter au site mais en ayant oublié son mot de passe

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.14 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Tous les clients s'affichent. ^|aucune ^|OK
^|All_I_C.15 ^|Compléter tous les champs avec les informations exactes du client, saississez le nouveau mot de passe + cliquer sur le CAPTCHA et Valider en cliquant sur "Modifier mon mot de passe"  . ^|Redirection vers la page de connexion avec le nouveau mot de passe ^|aucune ^|OK
^|All_I_C.16 ^|Compléter tous les champs avec des informations pas cohérentes avec celles du client  ^|Redirection vers la page de mot de passe oublié avec un message d'erreur ^|aucune ^|OK
^|All_I_C.17 ^|Cliquer sur le bouton "Annuler" ^|Redirection vers la page de connexion ^|aucune ^|OK

|====


==== 1.2 Compte client informations :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Mes informations
>|Objectif 4+| Vérifier qu'il est possible de consulter et modifier mes informations

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.1 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.2 ^|Sélectionner le bouton "Mes informations". ^|Toutes les informations concernant le client s'affichent + un bouton "Modifier" et un bouton "Changer de mot de passe". ^|aucune ^|OK
^|All_I_CCI.3 ^|Cliquer sur le bouton "Modifier" ^|Le client peut modifier ses informations personnelles et enregistrer une carte bleue si il le souhaite ^|aucune ^|OK
^|All_I_CCI.4 ^|Remplir les champs à modifier puis cliquer sur "Valider" ^| Une pop-up apparait, cliquez sur "OK" -> redirection vers la page des informations avec les nouvelles ^|aucune ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Modifier mon mot de passe
>|Objectif 4+| Vérifier qu'il est possible de modifier son mot de passe

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.5 ^|Cliquer sur le bouton "Changer de mot de passe" ^|Redirection vers un formulaire de changement de mot de passe ^| Être sur la page des informations du client ^|OK
^|All_I_CCI.6 ^|Remplir les champs pour modifier le mot de passe ^|Redirection vers la page de connexion ^|aucune ^|Ne fonctionne pas (à corriger pour plus tard)

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Accéder à mon panier et mes commandes
>|Objectif 4+| Vérifier qu'il est possible d'accéder à son panier et ses commandes

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.7 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.8 ^|Cliquer sur le bouton "Mon panier" ^|Redirection vers le panier du client avec les articles (ou non) ^|aucune ^|OK
^|All_I_CCI.9 ^|Cliquer sur le bouton "Mes commandes" ^|Redirection vers les informations des commandes passées par le client ^|Avoir recliquer sur le bonhomme au préalable ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Accéder à mes avis
>|Objectif 4+| Vérifier qu'il est possible d'accéder à ses avis

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.10 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.11 ^|Cliquer sur le bouton "Mes avis" ^|Redirection vers la liste des avis du client ^|aucune ^|OK
^|All_I_CCI.12 ^|Ajouter un avis sur un produit déjà commandé par le client et remplir les champs puis Valider ^|Redirection vers la liste des avis du client avec l'avis ajouté (l'image ne marche pas encore) ^|aucune ^|OK
^|All_I_CCI.13 ^|Modifier un avis en modifiant les champs de l'avis déjà préremplis puis valider  ^|Redirection vers la liste des avis du client avec l'avis ajouté (l'image ne marche pas encore) ^|aucune ^|OK
^|All_I_CCI.14 ^|Supprimer un avis en cliquant sur le bouton "Supprimer" et Valider ou  en cliquant sur "Modifier" puis "Supprimer" et Valider ^|Redirection vers la liste des avis du client avec l'avis supprimé ^|aucune ^|OK
^|All_I_CCI.15 ^|Supprimer, Modifier ou Ajouter un avis puis cliquer sur "Retour" ^|Redirection vers la liste des avis du client avec aucun changement ^|aucune ^|OK



|====

|====

>|Cas de test 4+|Test-01-02-05
>|Titre 4+|Mon panier
>|Objectif 4+| Vérifier qu'il est possible de gérer son panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.16 ^|Cliquer sur le panier en haut à droite ou sur "Mon Panier" ^|Redirection vers le panier du client ^|Être sur la page des informations du client dans le deuxième cas ^|OK




|====



==== 1.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Consulter les opérations d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter les opérations d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Voir opérations". ^|La page des opérations du compte du client s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2 ^|Cliquer sur le bouton "Voir opérations" sur un compte qui est cloture. ^|La page des opérations du compte du client s’affiche mais avec les boutons "enregistrer crédit" et "enregistrer débit" désactivé. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.3 ^|Cliquer sur le bouton "Retour gestion comptes". ^|La page de gestion des comptes du client s'ouvre et celle des opérations se ferme. ^| Un compte actif est sélectionné ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.4 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.5  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|Ok
^|All_G_COP.6  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|Ok
^|All_G_COP.7  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|Ok
 ^|All_G_COP.8  ^|Rentrer un montant de 1 dans le champ "Montant" et annuler débit. ^|Fermeture de la fenêtre des débits ^| Fenêtre des opérations est active et celle de enregistrer un débit aussi.
 ^|Ok
  
 

|====

|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Créditer un compte
>|Objectif 4+| Vérifier qu'il est possible de créditer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.9 ^|Cliquer sur le bouton "Enregistrer Crédit". ^|La page des crédits du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.10  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +100euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +50 euro
 ^|OK
 ^|All_G_COP.11  ^|Rentrer un montant 10 dans le champ "Montant" et annuler crédit. ^|Fermeture de la fenêtre des crédits ^| Fenêtre des opérations est active et celle de enregistrer un crédit aussi.
 ^|OK

  
 

|====

|====

>|Cas de test 4+|Test-01-03-04
>|Titre 4+|Virement compte à compte
>|Objectif 4+| Effectuer un virement d'un compte à un autre

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.12 ^|Cliquer sur le bouton "Effectuer Virement". ^|La page du virement du compte s’affiche. ^| Le compte num 44 du client Angelo est sélectionné  ^|OK
^|All_G_COP.13  ^|Choisir le numéro 201 dans le champ "Compte du destinataire" et un montant de 50 dans le champ "Montant". ^|On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte qui fait le virement a un solde de +2000.
^|Marche à moitié, le destinataire ne reçoit pas l'argent mais le débiteur perd l'argent
^|All_G_COP.14  ^|Choisir le numéro 201 dans le champ "Compte du destinataire" et un montant de 50000 dans le champ "Montant". ^|Blocage + Exception ^| Le compte sélectionné a un solde de +2000 euros, le découvert autorisé est de -1000 euros.
^|OK
^|All_G_COP.15  ^|Rentrer le numéro 164 dans le champ "Destinataire" et un montant de 100 dans le champ "Montant" et annuler le virement.  ^|La fenêtre des virements se ferme ^| Fenêtre des opérations est active et celle de effectuer un virement aussi.
^|OK
  
 
|====



==== 1.4 Gestion des prélèvements automatiques :

|====

>|Cas de test 4+|Test-01-04-01
>|Titre 4+|Consulter les prélèvements d'un client
>|Objectif 4+| Vérifier qu'il est possible de consulter les prélèvements d'un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CPA.1 ^|Cliquer sur le bouton "Voir prélèvements". ^|La page de gestion des prélèvements des comptes du client. ^| La fenêtre de gestion des comptes d'un client est active ^|OK
^|All_G_CPA.2 ^|Cliquer sur le bouton "Rechercher" ^|La liste des prélèvements de tous les comptes client est affichée. ^| La fenêtre de gestion des prélèvements est active. ^|OK
^|All_G_CPA.3 ^|Cliquer sur le bouton "Retour gestion comptes". ^|La page de gestion des comptes du client s'ouvre et celle des prélèvements se ferme. ^| La fenêtre de gestion des prélèvements est active. ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-04-02
>|Titre 4+|Création d'un nouveau prélèvement
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau prélèvement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CPA.4 ^|Cliquer sur le bouton "Nouveau prélèvement". ^|La fenêtre de création de prélèvement s'ouvre. ^| La fenêtre de gestion des prélèvements d'un client est active ^|OK
^|All_G_CPA.5 ^|Compléter les champs spécifiés et valider. ^|Un nouveau prélèvment est créé. ^|La fenêtre de création est active ^|OK
^|All_G_CPA.6 ^|Compléter tous les champs sauf un et valider. ^|Blocage ! + pop-up. ^|La fenêtre de création est active ^|OK
^|All_G_CPA.7 ^|Rentrer un Montant "0" et valider. ^|Blocage ! + pop-up. ^|La fenêtre de création est active ^|OK
^|All_G_CPA.8 ^|Rentrer un jour "0" ou "29" et valider. ^|Blocage ! + pop-up. ^|La fenêtre de création est active ^|OK
^|All_G_CPA.9 ^|Sélectionner aucun compte. ^|Blocage ! + pop-up. ^|La fenêtre de création est active ^|OK
^|All_G_CPA.10 ^|Compléter les champs et cliquer sur le bouton "Annuler". ^|Retour sur les informations des prélèvements. Le prélèvement n'est pas créé. ^|La fenêtre de création est active ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-04-03
>|Titre 4+|Modification d'un prélèvement
>|Objectif 4+| Vérifier qu'il est possible de modifier un prélèvement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CPA.11 ^|Cliquer sur le bouton "Modifier prélèvement". ^|La fenêtre de modification de prélèvement s'ouvre. ^| La fenêtre de gestion des prélèvements d'un client est active ^|OK
^|All_G_CPA.12 ^|Modifier les champs souhaités sauf celui du destinataire qui est maintenant désactivé et valider. ^|Le prélèvement sélectionné est modifié. ^|La fenêtre de modification est active et un prélèvement est sélectionné ^|OK
^|All_G_CPA.13 ^|Comme avec la création, si mauvaise saisie des champs et valider. ^|Blocage ! + pop-up. ^|La fenêtre de modification est active et un prélèvement est sélectionné  ^|OK
^|All_G_CPA.14 ^|Modifier les champs souhaités et valider. ^|Retour sur les informations des prélèvements. Le prélèvement reste inchangé. ^|La fenêtre de modification est active et un prélèvement est sélectionné ^|OK

  
 

|====

|====

>|Cas de test 4+|Test-01-04-04
>|Titre 4+|Suppresion d'un prélèvement
>|Objectif 4+| Vérifier qu'il est possible de supprimer un prélèvement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CPA.15 ^|Cliquer sur le bouton "Supprimer prélèvement". ^|Pop-up de confirmation de suppression, si "oui" le prélèvement est supprimer de la liste, si "non" la suppression est annuler. ^| La fenêtre de gestion des prélèvements d'un client est active et un prélèvement est sélection ^|OK

  
 

|====

==== 1.5 Générer un relevé PDF :

|====

>|Cas de test 4+|Test-01-04-05
>|Titre 4+|Génération d'un relevé PDF des comptes
>|Objectif 4+| Vérifier qu'il est possible de générer un relevé PDF des comptes d'un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CPDF.1 ^|Cliquer sur le bouton "Générer relevé PDF". ^|Une page de votre navigateur s'ouvre avec le relevé en question + le fichier est enregistré dans vos téléchargements.  ^| La fenêtre de gestion des comptes d'un client est active ^|OK

  
 

|====



=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.


==== 2.1 Gestion des employés :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Consulter les employés
>|Objectif 4+| Vérifier qu'il est possible de consulter les employés d'une agence

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.1 ^|Cliquer sur le bouton "Gestion" puis sur "Employés". ^|La page de gestion des employés s'affiche. ^| Être connecté en tant que Chef d'agence ^|OK
^|All_G_E.2 ^|Cliquer sur le bouton "Gestion". ^|Le bouton "Employé" est désactivé. ^| Être connecté en tant que Guichetier ^|OK
^|All_G_E.3 ^|Cliquer sur le bouton "Rechercher" ^|La liste des employés s'affiche. ^| La fenêtre de gestion des employés est active. ^|OK
^|All_G_E.4 ^|Cliquer sur le bouton "X" en haut à droite de la fenêtre. ^|La fenêtre principale s'ouvre et celle des employés se ferme . ^| La fenêtre de gestion des employés est active. ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-02-01-02
>|Titre 4+|Création d'un employé
>|Objectif 4+| Vérification de la création d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.5 ^|Cliquer sur le bouton "Créer employé". ^|La fenêtre de création des employés s'ouvre. ^| La fenêtre de gestion des employés est active. ^|OK
^|All_G_E.6 ^|Compléter les champs spécifiés et valider. ^|Un nouvel employé est créé. ^|La fenêtre de création des employés est active. ^|OK
^|All_G_E.7 ^|Compléter tous les champs sauf un et valider. ^|Blocage + Pop-up. ^|La fenêtre de création des employés est active. ^|OK
^|All_G_E.8 ^|Compléter le champ "ID Agence" avec un chiffre qui n'est pas entre 1 et 3. ^|Blocage + Pop-up. ^|La fenêtre de création des employés est active. ^|OK
^|All_G_E.9 ^|Compléter les champs et annuler ^|Retour sur les informations des employés ^|La fenêtre de création des employés est active. ^|OK


 
|====

|====

>|Cas de test 4+|Test-02-01-03
>|Titre 4+|Modification d'un employé
>|Objectif 4+| Vérification de la modification d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.10 ^|Cliquer sur le bouton "Modifier employé". ^|La fenêtre de modification des employés s'ouvre. ^| La fenêtre de gestion des employés est active ^|OK
^|All_G_E.11 ^|Modifier les champs spécifiés sauf le numéro d'agence qui est désactivé et valider. ^|L'employé selectionné est modifié. ^|La fenêtre de gestion des employés est active et avoir sélectionné un employé ^|OK
^|All_G_E.12 ^|Comme avec la création, si non-saisie des informations ou mauvaise saisie de l'ID de l'agence et valider . ^|Blocage + Pop-up ^|La fenêtre de gestion des employés est active et avoir sélectionné un employé ^|OK
^|All_G_E.13 ^|Modifier les champs spécifiés sauf le numéro d'agence qui est désactivé et annuler. ^|Retour sur les informations des employés. L'employé reste inchangé. ^|La fenêtre de gestion des employés est active et avoir sélectionné un employé ^|OK


 
|====

|====

>|Cas de test 4+|Test-02-01-04
>|Titre 4+|Suppression d'un employé
>|Objectif 4+| Vérification de la suppression d'un employé

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_E.14 ^|Cliquer sur le bouton "Supprimer employé". ^|La fenêtre de la liste des employés s'ouvre, quitter et revenir sur la fenêtre de gestions, l'employé sélectionné n'est plus là. ^| La fenêtre de gestion des employés est active et avoir sélectionné un employé ^|OK
 
|====

==== 2.2 Simuler un emprunt :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+| Simulation d'un emprunt
>|Objectif 4+| Vérifier qu'il est possible de simuler un emprunt avec ou sans assurance

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_SE.1 ^|Cliquer sur le bouton "Simuler un emprunt". ^|La fenêtre de simulation d'un emprunt s'ouvre.  ^| La fenêtre de gestion des clients est active
^|Ok
^|All_G_SE.2 ^|Compléter les champs "Montant", "Durée", "Type", et "Taux annuel" et valider. ^|La fenêtre du résultat de la simulation s'ouvre.  ^| La fenêtre de simulation de l'emprunt est active
^|OK, mais l'affichage n'ai pas correct (trop de chiffres après la virgule)
^|All_G_SE.3 ^|Compléter les champs précédent sauf un et valider. ^|Blocage, la fenêtre ne s'ouvre pas.  ^| La fenêtre de simulation de l'emprunt est active
^|OK
^|All_G_SE.4 ^|Compléter les champs précédent avec des caractères et non des chiffres et valider. ^|Blocage, la fenêtre ne s'ouvre pas.  ^| La fenêtre de simulation de l'emprunt est active
^|Ok
^|All_G_SE.5 ^|Compléter les champs précédent en mettant "oui" au champ "Simulation d'assurance" et en complétant le champ "Taux d'assurance" et valider. ^|La fenêtre du résultat de la simulation s'ouvre  ^| La fenêtre de simulation de l'emprunt est active
^|Pas ok, les calcul ne sont pas bons
^|All_G_SE.6 ^|Compléter les champs précédent en mettant "oui" au champ "Simulation d'assurance" et en mettant un caractère ou rien dans le champ "Taux d'assurance" et valider. ^|Blocage, la fenêtre ne s'ouvre pas.  ^| La fenêtre de simulation de l'emprunt est active
^|Ok
^|All_G_SE.7 ^|Compléter les champs spécifiés et Annuler. ^|Retour sur les informations des clients.  ^| La fenêtre de simulation de l'emprunt est active
^|Ok

|====



==== 2.3 Gestion des opérations :

|====

>|Cas de test 4+|Test-02-03-01
>|Titre 4+|Faire un débit exceptionnelle sur un compte
>|Objectif 4+| Vérifier qu'il est possible de faire un débit exceptionnelle sur un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP².1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP².2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|Ok
^|All_G_COP².3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|Ok
^|All_G_COP².4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up de confirmation du débit ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros + être connecté en tant que Chef d'agence (b b)
 ^|Ok
 ^|All_G_COP².5  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up de confirmation du débit + pop-up erreur car connecté en tant que guichetier (LN Levieux) ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros + être connecté en tant que guichetier (LN Levieux)
 ^|Ok
 ^|All_G_COP².6  ^|Rentrer un montant de 1 dans le champ "Montant" et annuler débit. ^|Fermeture de la fenêtre des débits ^| Fenêtre des opérations est active et celle de enregistrer un débit aussi.
 ^|Ok
  
 
|====
