= Cahier De Test - Disguise'Hub
:toc:
:toc-title: Sommaire

:Entreprise: Disguise'Hub
:Equipe:  

.Créé par : Angelo Nichele
Créé pour : Tester les fonctionnalités du site web Disguise'Hub

 



== I. Introduction
=== 1. Objet :
Ce document a été produit dans le cadre d'un projet d'élaboration d'un site de vente en ligne de déguisement pour tester les différentes fonctionnalités de ce dernier.


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. 


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Informations du client :
==== 1.1 Connexion compte client :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un compte client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau compte client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.1 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre de connexion au site s'ouvre. ^| Avoir le site d'ouvert ^|OK
^|All_I_C.2 ^|Cliquer sur "Je n'ai pas encore de compte". ^|La fenêtre de création d'un compte client s'ouvre ^|aucune ^|OK
^|All_I_C.3 ^|Compléter tous les champs en étant bien valides sauf un et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.4 ^|Rentrer un numéro de téléphone "vgvhch" et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.5 ^|Rentrer un mail "test@gmail." et s'inscrire. ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.6 ^|Rentrer un mot de passe inadéquat (sans majuscule par exemple) ^|Blocage ! + pop-up. ^|aucune ^|OK
^|All_I_C.7 ^|Compléter les champs et ne pas cliquer sur le CAPTCHA. ^|Bouton "s'inscrire" est grisé + incapacité à cliquer dessus ^|aucune ^|OK
^|All_I_C.8 ^|Compléter les champs en étant bien valides + cliquer sur le CAPTCHA ^|Bouton "s'inscrire" est orangé + on peut cliquer dessus et s'inscrire sur le site ^|OK
^|All_I_C.9 ^|Cliquer sur "J'ai déjà un compte" ^|Redirection vers la page de connexion ^|OK



|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Connexion au site
>|Objectif 4+| Vérifier qu'il est possible de se connecter au site avec un compte client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.10 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre de connexion au site s'ouvre.  ^|Avoir le site d'ouvert ^|OK
^|All_I_C.11 ^|Remplir les champs, cliquer sur le CAPTCHA et cliquer sur "Se connecter" ^|Renvoie sur la page des informations du client ^|aucune ^|OK
^|All_I_C.12 ^|Comme avec la création du compte client, si mauvaise saisie des différents champs et valider. ^|Blocage + pop-up. ^|aucune ^|OK
^|All_I_C.13 ^|Remplir les champs, etc + cliquer sur la case "Se souvenir de moi" ^|Renvoie sur la page des informations du client mais en se déconnectant, l'adresse mail du client reste préremplie ^|aucune ^|OK

|====

|====

>|Cas de test 4+|Test-01-01-03
>|Titre 4+|Connexion au site avec le mot de passe oublié
>|Objectif 4+| Vérifier qu'il est possible de se connecter au site mais en ayant oublié son mot de passe

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_C.14 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Tous les clients s'affichent. ^|aucune ^|OK
^|All_I_C.15 ^|Compléter tous les champs avec les informations exactes du client, saississez le nouveau mot de passe + cliquer sur le CAPTCHA et Valider en cliquant sur "Modifier mon mot de passe"  . ^|Redirection vers la page de connexion avec le nouveau mot de passe ^|aucune ^|OK
^|All_I_C.16 ^|Compléter tous les champs avec des informations pas cohérentes avec celles du client  ^|Redirection vers la page de mot de passe oublié avec un message d'erreur ^|aucune ^|OK
^|All_I_C.17 ^|Cliquer sur le bouton "Annuler" ^|Redirection vers la page de connexion ^|aucune ^|OK

|====


==== 1.2 Compte client informations :


|====

>|Cas de test 4+|Test-01-02-01
>|Titre 4+|Mes informations
>|Objectif 4+| Vérifier qu'il est possible de consulter et modifier mes informations

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.1 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.2 ^|Sélectionner le bouton "Mes informations". ^|Toutes les informations concernant le client s'affichent + un bouton "Modifier" et un bouton "Changer de mot de passe". ^|aucune ^|OK
^|All_I_CCI.3 ^|Cliquer sur le bouton "Modifier" ^|Le client peut modifier ses informations personnelles et enregistrer une carte bleue si il le souhaite ^|aucune ^|OK
^|All_I_CCI.4 ^|Remplir les champs à modifier puis cliquer sur "Valider" ^| Une pop-up apparait, cliquez sur "OK" -> redirection vers la page des informations avec les nouvelles ^|aucune ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-02
>|Titre 4+|Modifier mon mot de passe
>|Objectif 4+| Vérifier qu'il est possible de modifier son mot de passe

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.5 ^|Cliquer sur le bouton "Changer de mot de passe" ^|Redirection vers un formulaire de changement de mot de passe ^| Être sur la page des informations du client ^|OK
^|All_I_CCI.6 ^|Remplir les champs pour modifier le mot de passe ^|Redirection vers la page de connexion ^|aucune ^|Ne fonctionne pas (à corriger pour plus tard)

|====

|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Accéder à mon panier et mes commandes
>|Objectif 4+| Vérifier qu'il est possible d'accéder à son panier et ses commandes

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.7 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.8 ^|Cliquer sur le bouton "Mon panier" ^|Redirection vers le panier du client avec les articles (ou non) ^|aucune ^|OK
^|All_I_CCI.9 ^|Cliquer sur le bouton "Mes commandes" ^|Redirection vers les informations des commandes passées par le client ^|Avoir recliquer sur le bonhomme au préalable ^|OK


|====

|====

>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Accéder à mes avis
>|Objectif 4+| Vérifier qu'il est possible d'accéder à ses avis

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.10 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|Les différents éléments du compte client s'affichent (les commandes, les avis, les informations,...) ^|Le client doit être déjà connecté ^|OK
^|All_I_CCI.11 ^|Cliquer sur le bouton "Mes avis" ^|Redirection vers la liste des avis du client ^|aucune ^|OK
^|All_I_CCI.12 ^|Ajouter un avis sur un produit déjà commandé par le client et remplir les champs puis Valider ^|Redirection vers la liste des avis du client avec l'avis ajouté (l'image ne marche pas encore) ^|aucune ^|OK
^|All_I_CCI.13 ^|Modifier un avis en modifiant les champs de l'avis déjà préremplis puis valider  ^|Redirection vers la liste des avis du client avec l'avis ajouté (l'image ne marche pas encore) ^|aucune ^|OK
^|All_I_CCI.14 ^|Supprimer un avis en cliquant sur le bouton "Supprimer" et Valider ou  en cliquant sur "Modifier" puis "Supprimer" et Valider ^|Redirection vers la liste des avis du client avec l'avis supprimé ^|aucune ^|OK
^|All_I_CCI.15 ^|Supprimer, Modifier ou Ajouter un avis puis cliquer sur "Retour" ^|Redirection vers la liste des avis du client avec aucun changement ^|aucune ^|OK



|====

|====

>|Cas de test 4+|Test-01-02-05
>|Titre 4+|Mon panier
>|Objectif 4+| Vérifier qu'il est possible de gérer son panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.16 ^|Cliquer sur le panier en haut à droite ou sur "Mon Panier" ^|Redirection vers le panier du client (il peut être vide si aucun produit n'ont été ajouté) ^|Être sur la page des informations du client dans le deuxième cas ^|OK
^|All_I_CCI.17 ^|Si il y a un ou plusieurs produits, on peut modifier la quantité du produit et donc le supprimer ^|Affichage en direct du produit et de sa quantité ^|aucune ^|OK
^|All_I_CCI.18 ^|Si il y a un ou plusieurs produits, on peut cliquer sur "Commander" mais nous verrons ça plus tard ^|Redirection vers la page de commande ^|aucune ^|OK



|====

|====

>|Cas de test 4+|Test-01-02-06
>|Titre 4+|Mes commandes
>|Objectif 4+| Vérifier qu'il est possible de gérer ses commandes

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_CCI.19 ^|Cliquer sur "Mes commandes" ^|Redirection vers la liste des commandes en cours ou déjà effectuées ^|Être sur la page des informations du client ^|OK
^|All_I_CCI.20 ^|Accéder au détail d'une commande en cliquant sur "Ma facture" ^|Affichage des détails de la commande ^|aucune ^|OK
^|All_I_CCI.21 ^|Procéder au paiement de la commande afin qu'elle puisse être préparée (nous verrons en détail cela après) ^|Redirection vers la page des moyens de paiement ^|aucune ^|OK
^|All_I_CCI.22 ^|Procéder au paiement de la commande afin qu'elle puisse être préparée (nous verrons en détail cela après) puis cliquer sur "Retour" ^|Retour sur la liste des commandes du client ^|aucune ^|OK


|====



==== 1.3 Déconnexion compte client / Administration :

|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Déconnexion au site
>|Objectif 4+| Vérifier qu'il est possible de se déconnecter du site

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_DCC-A.1 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre des informations du client s'ouvre.  ^|Être connecté au site ^|OK
^|All_I_DCC-A.2 ^|Cliquer sur "Déconnexion" ^|Retour sur la page d'accueil du site en étant déconnecté  ^|aucune ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Ne plus se souvenir
>|Objectif 4+| Vérifier qu'il est possible de ne plus se souvenir de son adresse mail

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_DCC-A.3 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre des informations du client s'ouvre.  ^|Être connecté au site ^|OK
^|All_I_DCC-A.4 ^|Cliquer sur "Ne plus se souvenir" ^|Redirection vers la page des informations du client sans le bouton "Ne plus se souvenir" -> cookie détruit  ^|aucune ^|OK
^|All_I_DCC-A.5 ^|Cliquer sur "Déconnexion" ^|Retour sur la page d'accueil du site en étant déconnecté et avec le cookie détruit ^|aucune ^|OK
^|All_I_DCC-A.6 ^|Recliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre de connexion au site s'ouvre sans l'adresse mail de préremplie ^|aucune ^|OK

  
 

|====

|====

>|Cas de test 4+|Test-01-03-03
>|Titre 4+|Administration
>|Objectif 4+| Vérifier qu'il est possible d'accéder à l'administration du site

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_I_DCC-A.7 ^|Cliquer sur le bouton du bonhomme blanc en haut à droite du site. ^|La fenêtre des informations du client s'ouvre.  ^|Être connecté au site ^|OK
^|All_I_DCC-A.8 ^|Mettre l'attribut "isAdmin" à 1 dans la table Client de la Base de Données ^|La personne peut accéder à la partie Administration du site + bouton "Administration" visible  ^|aucune ^|OK
^|All_I_DCC-A.9 ^|Cliquer sur le bouton "Administration" ^|Redirection vers la page de gestion des produits ^|aucune ^|OK
^|All_I_DCC-A.10 ^|Gestion des produits (Ajouter/Modifier/Supprimer/Quantité en stock) ^|Modification, ajout des produits,etc.. (Modifier et Supprimer ne marche pas pour l'instant) ^|aucune ^|OK


 

|====




=== 2. Commandes :

==== 2.1 Ajouter un produit au panier :

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Consulter une catégorie
>|Objectif 4+| Vérifier qu'il est possible de consulter un catégorie

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_AP.1 ^|Cliquer sur le logo du site en haut ^|La page avec tous les produits et toutes les catégories s'affichent ^|Avoir le site d'ouvert ^|OK
^|All_C_AP.2 ^|Cliquer sur l'une des 7 catégories sur la page ou les sous-catégories dans le header ^|La page avec tous les produits de la catégorie ou sous-catégorie s'affiche ^|aucune ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-02-01-02
>|Titre 4+|Consulter un produit
>|Objectif 4+| Vérifier qu'il est possible de consulter un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_AP.3 ^|Cliquer sur le logo du site en haut ^|La page avec tous les produits et toutes les catégories s'affichent ^|Avoir le site d'ouvert ^|OK
^|All_C_AP.4 ^|Descendre un peu puis cliquer un produit ^|La page du détail du produit s'affiche (taille, couleur, description, notes, avis,...) ^|aucune ^|OK
  
 

|====

|====

>|Cas de test 4+|Test-02-01-03
>|Titre 4+|Ajouter un produit au panier
>|Objectif 4+|Vérifier qu'il est possible d'ajouter un produit au panier

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_AP.5 ^|Aller sur la page du détail d'un produit ^|Les détails du produit sont affichés avec un bouton "Ajouter au panier" et la quantité en stock^|Avoir cliqué sur un produit ^|OK
^|All_C_AP.6 ^|Cliquer sur "Ajouter au panier" ^|Le bouton se change pour nous indiquer que le produit est bien dans le panier ^|aucune ^|OK
^|All_C_AP.7 ^|Aller sur le panier en cliquant sur le nouveau bouton "Dans le panier" ou sur le panier en haut à droite du site^|La page du panier avec le/les produits s'ouvre ^|aucune ^|OK
^|All_C_AP.8 ^|Modifier la quantité souhaitée du produit (comme on a déjà vu plus haut) ^|La quantité s'actualise, le montant de la commande aussi ^|aucune ^|OK


 
|====


==== 2.2 Passer commande :

|====

>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Commander
>|Objectif 4+|Vérifier qu'il est possible de commander un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_PC.1 ^|Se connecter pour pouvoir passer une commande si pas encore connecté ^|Client connecté sur le site  ^|aucune ^|Ok
^|All_C_PC.2 ^|Aller sur le panier en cliquant sur le panier en haut à droite du site^|La page du panier avec le/les produits s'ouvre ^|aucune ^|OK
^|All_C_PC.3 ^|Remplir le champ "Pays" et Cliquer sur "Commander" ^|Redirection vers la page de commande avec le détail de la commande (montant total, livraison, statut, ...) ^|aucune ^|OK



|====

|====

>|Cas de test 4+|Test-02-02-02
>|Titre 4+|Payer avec une carte bleue
>|Objectif 4+|Vérifier qu'il est possible de payer avec une carte bleue

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_PC.4 ^|Cliquer sur "Procéder au paiement" depuis la page du détail de la commande ou depuis la liste des commandes du client (comme vu précédement) ^|Redirection vers une page de choix du paiement  ^|aucune ^|Ok
^|All_C_PC.5 ^|Sélectionner Carte Bancaire ^|Un formulaire à remplir s'affiche  ^|aucune ^|Ok
^|All_C_PC.6 ^|Remplir le formulaire avec des informations valides (bon nombre de caractère,etc..) et cliquer sur "Valider" ^|Redirection vers la page du paiement effectué avec la facture (le détail)  ^|aucune ^|Ok
^|All_C_PC.7 ^|Cliquer sur "Retouner à la liste des commandes" ^|Redirection vers la page des commandes du client  ^|aucune ^|Ok


|====

|====

>|Cas de test 4+|Test-02-02-03
>|Titre 4+|Payer avec Paypal
>|Objectif 4+|Vérifier qu'il est possible de payer avec Paypal

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_PC.8 ^|Cliquer sur "Procéder au paiement" depuis la page du détail de la commande ou depuis la liste des commandes du client (comme vu précédement) ^|Redirection vers une page de choix du paiement  ^|aucune ^|Ok
^|All_C_PC.9 ^|Sélectionner Paypal ^|Redirection vers la page de paiement Paypal  ^|aucune ^|Ok
^|All_C_PC.10 ^|Cliquer sur "Payer" ^|Redirection vers la page du paiement effectué avec la facture (le détail)  ^|aucune ^|Ok
^|All_C_PC.11 ^|Cliquer sur "Retouner à la liste des commandes" ^|Redirection vers la page des commandes du client  ^|aucune ^|Ok

|====

|====

>|Cas de test 4+|Test-02-02-04
>|Titre 4+|Payer avec un virement bancaire
>|Objectif 4+|Vérifier qu'il est possible de payer avec un virement bancaire

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_C_PC.12 ^|Cliquer sur "Procéder au paiement" depuis la page du détail de la commande ou depuis la liste des commandes du client (comme vu précédement) ^|Redirection vers une page de choix du paiement  ^|aucune ^|Ok
^|All_C_PC.13 ^|Sélectionner Virement Bancaire ^|Redirection vers la page de paiement Virement Bancaire  ^|aucune ^|Ok
^|All_C_PC.14 ^|Remplir le formulaire avec des informations valides du Nom, BIC et IBAN puis cliquer sur payer  ^|Redirection vers la page du paiement effectué avec la facture (le détail) ^|aucune ^|Ok
^|All_C_PC.15 ^|Cliquer sur "Retouner à la liste des commandes" ^|Redirection vers la page des commandes du client  ^|aucune ^|Ok

|====


=== 3. Recherche :

==== 3.1 Rechercher des produits :

|====

>|Cas de test 4+|Test-03-01-01
>|Titre 4+|Rechercher un produit
>|Objectif 4+|Vérifier qu'il est possible de rechercher un produit

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_R_RP.1 ^|Cliquer sur le bouton recherche en haut à gauche du site ^|Une page de recherche de produits apparait avec une barre ^|aucune ^|Ok
^|All_R_RP.2 ^|Écrire "Batman" dans la barre puis entrer ^|Tous les produits avec le nom "Batman" dedans s'affichent ^|aucune ^|Ok
^|All_R_RP.3 ^|Selectionner "Prix croissant" dans le menu déroulant ^|Les produits avec "Batman" dedans s'affichent par ordre croissant des prix ^|aucune ^|Ok
^|All_R_RP.4 ^|Selectionner "Prix décroissant" dans le menu déroulant ^|Les produits avec "Batman" dedans s'affichent par ordre décroissant des prix ^|aucune ^|Ok

|====


=== 4. Pages Futures :

|====

>|Cas de test 4+|Test-04-01-01
>|Titre 4+|Page à faire plus tard
>|Objectif 4+|Vérifier qu'un affichage apparait sur les pages futures

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_PF.1 ^|Cliquer sur un des liens dans le menu footer (Plan du site par exemple) ^|Un affichage apparait comme quoi la page sera disponible plus tard ^|aucune ^|Ok
