@startuml DCU - Utilisateur
skinparam actorStyle awesome
left to right direction

actor "Visiteur" as v #FEFECE
usecase "Recherche de produits" as v1 #F0F8FF
usecase "Affichage des produits" as v2 #F0F8FF
usecase "Création d'un compte DISGUISE’HUB" as v3 #F0F8FF
v --> v1
v --> v2
v --> v3

actor "Utilisateur" as s #FEFECE
usecase "Me connecter à mon compte" as s1 #F0F8FF
usecase "Recherche de produits" as s2 #F0F8FF
usecase "Affichage des produits" as s3 #F0F8FF
usecase "Détails du produit" as s4 #F0F8FF
usecase "Ajout au panier" as s5 #F0F8FF
usecase "Passage de commande" as s6 #F0F8FF
usecase "Consulter mon programme de fidélité" as s7 #F0F8FF
usecase "Avis et évaluations" as s8 #F0F8FF
usecase "Gestion du profil client" as s9 #F0F8FF
usecase "Suivi de commande" as s10 #F0F8FF
usecase "Guide de taille interactif" as s11 #F0F8FF
usecase "Liste des favoris" as s12 #F0F8FF
usecase "Newsletter" as s13 #F0F8FF
s --> s1
s --> s2
s --> s3
s --> s4
s --> s5
s --> s6
s --> s7
s --> s8
s --> s9
s --> s10
s --> s11
s --> s12
s --> s13

v <|- s

@enduml