@startuml Diagramme de séquence - Application IOT
title Diagramme de séquence - Application IOT
hide footbox

actor "Utilisateur" as u
participant "Application JavaFX" as a
participant "Fichier(s) data" as d

u -> a: Demande de visualisation des données
a -> d: Récupération des données
d --> a: data
a --> u: Affiche les données

@enduml