@startuml DCU - Utilisateur
skinparam actorStyle awesome
left to right direction

actor "Visiteur" as v #FEFECE
usecase "Ajout au panier" as v1 #F0F8FF
usecase "Affichage des produits" as v2 #F0F8FF
usecase "Recherche de produits" as v3 #F0F8FF
usecase "Détails du produit" as v4 #F0F8FF
usecase "Création d'un compte" as v5 #F0F8FF
usecase "Guide de taille interactif" as v6 #F0F8FF
v --> v1
v --> v2
v --> v3
v --> v4
v --> v5
v --> v6

actor "Utilisateur" as u #FEFECE
usecase "Passage de commande" as u1 #F0F8FF
usecase "Avis et évaluations" as u2 #F0F8FF
usecase "Me connecter à mon compte" as u3 #F0F8FF
usecase "Gestion du profil client" as u4 #F0F8FF
usecase "Consulter mon programme de fidélité" as u5 #F0F8FF
usecase "Suivi de commande" as u6 #F0F8FF
usecase "Liste des favoris" as u7 #F0F8FF
usecase "Newsletter" as u8 #F0F8FF
u --> u1
u --> u2
u --> u3
u --> u4
u --> u5
u --> u6
u --> u7
u --> u8

v <|- u

@enduml